# Generated by Django 5.0.10 on 2025-01-02 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscriptionprice_featuted_subscriptionprice_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='featuted',
        ),
        migrations.AddField(
            model_name='subscriptionprice',
            name='featured',
            field=models.BooleanField(default=True, help_text='For Django Price Page'),
        ),
        migrations.AddField(
            model_name='subscriptionprice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionprice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='order',
            field=models.IntegerField(default=-1, help_text='For Django Pricing Page'),
        ),
    ]
