# Generated by Django 5.0.10 on 2025-01-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_remove_subscriptionprice_featuted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['order', 'featured', 'updated']},
        ),
    ]
