# Generated by Django 5.0.10 on 2025-01-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_usersubscription_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('incomplete', 'Incomplete'), ('canceled', 'Canceled')], max_length=120, null=True),
        ),
    ]
